# Generated by Django 2.0.13 on 2019-04-09 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190409_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='portfolio',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Pictures'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 5, 13, 57, 734255, tzinfo=utc)),
        ),
    ]
