# Generated by Django 2.0.13 on 2019-04-09 08:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190409_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('animals', 'Animals'), ('cars', 'Cars'), ('cities', 'Cities'), ('fitness', 'Fitness'), ('motorcycles', 'Motorcycles'), ('people', 'People'), ('space', 'Space'), ('technology', 'Technology')], default='nature', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 8, 28, 20, 816073, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='categories',
            name='images',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Pictures'),
        ),
    ]
