# Generated by Django 2.0.13 on 2019-04-10 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190410_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='portfolio_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='portfolio',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Pictures'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 9, 1, 3, 334517, tzinfo=utc)),
        ),
    ]
