# Generated by Django 2.0.13 on 2019-04-10 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190410_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 9, 22, 16, 964872, tzinfo=utc)),
        ),
    ]
