# Generated by Django 2.0.13 on 2019-04-10 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190410_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='portfolio',
            new_name='picture',
        ),
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 9, 38, 59, 868984, tzinfo=utc)),
        ),
    ]
