# Generated by Django 2.0.13 on 2019-04-10 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190410_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Pictures', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 9, 40, 12, 7747, tzinfo=utc)),
        ),
    ]
