# Generated by Django 2.0.13 on 2019-04-12 04:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190412_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 12, 4, 30, 2, 590206, tzinfo=utc)),
        ),
    ]
