# Generated by Django 2.0.13 on 2019-04-13 05:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190412_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 5, 2, 47, 772084, tzinfo=utc)),
        ),
    ]
