# Generated by Django 2.0.13 on 2019-04-13 06:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20190413_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 6, 3, 13, 929031, tzinfo=utc)),
        ),
    ]
