# Generated by Django 2.0.13 on 2019-04-13 06:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190413_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 13, 6, 13, 50, 481749, tzinfo=utc)),
        ),
    ]
