# Generated by Django 2.0.13 on 2019-04-15 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190413_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 7, 42, 3, 472352, tzinfo=utc)),
        ),
    ]
