# Generated by Django 2.0.13 on 2019-04-15 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20190415_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 15, 9, 27, 51, 571273, tzinfo=utc)),
        ),
    ]
