# Generated by Django 2.0.13 on 2019-04-16 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20190416_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 6, 34, 38, 395386, tzinfo=utc)),
        ),
    ]
