# Generated by Django 2.0.13 on 2019-04-16 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20190416_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 13, 58, 15, 216615, tzinfo=utc)),
        ),
    ]
