# Generated by Django 2.0.13 on 2019-04-19 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20190416_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 5, 50, 0, 834251, tzinfo=utc)),
        ),
    ]
