# Generated by Django 2.0.13 on 2019-04-20 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190419_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 3, 54, 23, 257807, tzinfo=utc)),
        ),
    ]
