# Generated by Django 2.0.13 on 2019-04-20 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_auto_20190420_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 20, 4, 21, 16, 328315, tzinfo=utc)),
        ),
    ]
