# Generated by Django 2.0.13 on 2019-04-22 05:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20190420_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 5, 23, 50, 170058, tzinfo=utc)),
        ),
    ]
