# Generated by Django 2.0.13 on 2019-04-16 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_auto_20190415_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 6, 34, 38, 398507, tzinfo=utc)),
        ),
    ]
