# Generated by Django 2.0.13 on 2019-04-16 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 6, 45, 57, 312768, tzinfo=utc)),
        ),
    ]
