# Generated by Django 2.0.13 on 2019-04-16 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_auto_20190416_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 16, 10, 18, 5, 422443, tzinfo=utc)),
        ),
    ]
