# Generated by Django 2.0.13 on 2019-04-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_auto_20190416_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
